# Generated by Django 6.0.4 on 2026-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_reward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
