# Generated by Django 6.0.4 on 2026-05-21 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='score',
            new_name='communication',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='task_status',
        ),
        migrations.AddField(
            model_name='performance',
            name='evaluation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='final_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='innovation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='remarks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='task_completion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='teamwork',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
