# Generated by Django 5.2.13 on 2026-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_rename_score_performance_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
