# Generated by Django 6.0.4 on 2026-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_performance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
